### PR TITLE
Physio viz

### PR DESCRIPTION
**Pull request by CalebUAz**
added EEG visualization tool

### CODE REVIEW

**Review by adarshp — CHANGES_REQUESTED** [review]
If record_screen and record_screen.scpt both work, can you remove the record_screen.scpt file?

**Comment by adarshp** [comment]
@CalebUAz - also, looks like there is a merge conflict in server_rest_state.py - could you please fix that?

**Comment by CalebUAz** [comment]
> If record_screen and record_screen.scpt both work, can you remove the record_screen.scpt file?

I will push bash script after I complete working on that onto the AppleScript-changes branch and then git rid of record_screen and record_screen.scpt.

**Comment by CalebUAz** [comment]
> 

Done!

**Comment by CalebUAz** [comment]
> @CalebUAz - also, looks like there is a merge conflict in server_rest_state.py - could you please fix that?

Done!

**Comment by adarshp** [comment]
> I will push bash script after I complete working on that onto the AppleScript-changes branch and then git rid of record_screen and record_screen.scpt.

Ok, sounds good! I will wait for the bash script before merging this PR.

**Comment by CalebUAz** [comment]
> Ok, sounds good! I will wait for the bash script before merging this PR.

#375 done!

**Pull request closed without merging**
