### PR TITLE
Discrete Events (Button Press Event)

### PR DESCRIPTION
**Pull request by Adi-UA**
This PR adds functionality to detect discrete events. It specifically adds functionality to detect when a player presses a button, but it also adds the `ModBlocks` class, which can register any other new `Blocks` in the future by adding the relevant lines for the block. The class file contains more detailed information on how to do this which can be used to add new detector blocks easily.

The button event is only triggered when the player presses the new button added by this PR called the `ASIST Button`. It can be found in the Minecraft Creative menu under the Redstone tab, but it currently lacks a texture, so it shows up as a black and purple cube both in the inventory and in the world (after it is placed). 

When the button is pressed, a Hashmap output is printed to the terminal containing information about what the event was, the coordinates of the event, the time of occurrence (system date and time), and the player that caused the event.

NOTE: The current world on Vanga uses regular Minecraft buttons, not the new buttons added in this PR, so pressing buttons in the current version of the world will not print any output. 

NOTE: The button has defined borders (the same as normal Minecraft buttons) within which the player must right-click to register a press. Since the Block lacks a texture at the moment, it can be slightly confusing to understand where to click because the edges of the black and purple cube texture fall outside the defined boundaries; hence they don't register as a press.

### CODE REVIEW

**Comment by adarshp** [comment]
@Adi-UA Thanks! This looks excellent - I will try it out now and if it works for me I'll merge it.

**Comment by adarshp** [comment]
@Adi-UA In the meantime, could you please run `clang-format` on the Java files under `external/malmo/Minecraft/src/main/java` - some line wrapping and consistent formatting should help with readability. The following command should do the trick:

```
find external/malmo/Minecraft/src/main/java/ -name *.java | parallel --bar clang-format -i {}
```

The above command relies on GNU Parallel and clang-format, if you don't already have them you can install them with:

```
sudo apt-get install -y parallel clang-format
```

**Comment by Adi-UA** [comment]
Yes, I'll do that right away.

I also think I found a way to shorten the code. I'll update both in a commit.

**Comment by adarshp** [comment]
image

image

Cool! I will merge.

**Pull request merged**
