### PR TITLE
Adding Gaze raw data to the database

### PR DESCRIPTION
**Pull request by paulosoaresua**

### CODE REVIEW

**Comment by paulosoaresua** [comment]
Tested in Gauss by commenting out the eeg and fnirs lines to save time. Gaze data is correctly saved under `/space/paulosoares/tomcat/tomcat.db`.

**Review by adarshp — CHANGES_REQUESTED** [review]
Looks mostly good! Just a couple of small changes needed:

1. Enable foreign key constraints before inserting the data (just above line 132 in `process_gaze_data.py`) -- add this line: `db_connection.execute("PRAGMA foreign_keys = 1;")`
2. Update `metadata.yml` with descriptions of the columns, following the examples for the other tables.

**Comment by adarshp** [comment]
@paulosoaresua  - also, can you update the `build_database_from_scratch.sh` script to use chained commands with `&&` so that the script exits with an error when any of the invoked Python scripts fail?

**Comment by paulosoaresua** [comment]
@adarshp will, do, but notice `master` uses individual python calls. That's why I changed it after merging with it.

Also, I wrote this code based on the fnirs one. The foreign_key validation is also missing there (line 151 of the `process_fnirs_data.py`)

**Comment by adarshp** [comment]
@paulosoaresua  

Re: individual python calls - that's a mistake on my part, I should have asked @eduongAZ to chain them.

Re: foreign key validation missing in process_fnirs_data.py - again a mistake on my part, can you add that line to process_fnirs_data.py as well?

**Comment by paulosoaresua** [comment]
@adarshp No problem. Done.

**Review by adarshp — APPROVED** [review]

**Comment by adarshp** [comment]
Thanks @paulosoaresua !

**Pull request merged**
