### PR TITLE
Xdf to csv conversion

### PR DESCRIPTION
**Pull request by CalebUAz**
`XDF_to_csv_conversion.py`  does the following:

- Reads all XDF files.  
-  Iterates thought all Physio streams streams individually. 
- Reads start and stop time stamps from XDF file. Uses these timestamps to create a date-timestamp distribution. 
- Creates a data frame with all the physio stream data with the date-timestamp distribution.
- Creates a label distraction from start to stop timestamp Baseline task and Minecraft metadata. Then, syncs all this information with data frame. 
- Removes data before start and stop time stamps from XDF file. 
- Exports the data frame as CSV file and pickle file. 

`run_minecraft_metadata_validation.py` was updated so that it uses the trial stop instead of mission stop, in case we abort mission early.

### CODE REVIEW

**Review by adarshp — COMMENTED** [review]
@CalebUAz:

- How many XDF files are produced per team? It looks like this script merges information from multiple XDF files, but we shouldn't be merging information from multiple teams (at least not at the initial stage).

**Comment by CalebUAz** [comment]
> @CalebUAz:
> 
> * How many XDF files are produced per team? It looks like this script merges information from multiple XDF files, but we shouldn't be merging information from multiple teams (at least not at the initial stage).

-->**So we have 3 XDF files and `XDF_to_csv_conversion.py` generated NIRS.csv, EEG.csv and Gaze.csv for each participant (we'd have 9 csv files in total). So, I haven't merged any information.** 
Like this:
image

> * Also, could you please resolve the merge conflicts?

   -->**Done!**

**Comment by adarshp** [comment]
Thanks for clarifying, @CalebUAz ! One other point - can you turn off the generation of the .pkl files by default? I think having the pkl file is one redundancy step too many (we already have duplicate data between the XDF and CSV files). You could have a command line flag for a user to optionally generate a .pkl file if they so desire.

**Comment by CalebUAz** [comment]
> Thanks for clarifying, @CalebUAz ! One other point - can you turn off the generation of the .pkl files by default? I think having the pkl file is one redundancy step too many (we already have duplicate data between the XDF and CSV files). You could have a command line flag for a user to optionally generate a .pkl file if they so desire.

@adarshp Done!

**Pull request merged**
