### PR TITLE
add craftItem mission

### PR DESCRIPTION
**Pull request by JiangfengLi**
Created "addCraftItemPhase" and "addMaterialsInUsersInventory" function, set "this.shouldaddMaterialsInUsersInventory" to true in "beforePhaseTrasition" function, create if statement to see whether "shouldaddMaterialsInUsersInventory" is true and add three planks as well as two sticks and set shouldaddMaterialsInUsersInventory to false if it holds in "updateScene" function inside "TutorialMission.java" file

### CODE REVIEW

**Comment by JiangfengLi** [comment]
> I have just seen your implementation. There are some adjustments to be done. Exceptions will be thrown trying to run the tutorial mission. Did you execute the tutorial mission after those changes?

Alright, I will update the latest functional appropriately version

**Comment by paulosoaresua** [comment]
Great, here are the issues I noticed:

1. In the method addCraftItemPhase there's a reference to the object approachPoolsPhase that is never created;
2. Instead of creating an ItemType passing a string, use the static enumerator in the class ItemType. (e.g. ItemType.WOODEN_AXE);
3. The object approachPoolsPhase in the method addApproachPoolsPhase, must become global so you access it in another method;
4. In the method addMaterialsInUsersInventory, don't create the object BlockType directly but use the static enumerator in this class (e.g. BlockType.PLANKS);
5. addItemToInventory receives a ItemType as argument not a BlockType;
6. In the method beforePhaseTrasition you must check if the current phase is equal to the approachPoolsPhase (the one you must make global as stated in item 3) not the craftItemPhase (this one doesn't need to be global).

**Comment by paulosoaresua** [comment]
The code seems to be correct. Please, include meaningful images in the texture1.png file. I see you're referencing a texture2.png file in your .json but there's no texture2.png there. Let's stick with texture1.png until we fill all the space available. You can use the photoshop file I sent to you to add the images you need there.

**Comment by paulosoaresua** [comment]
Also, please adjust the documentation of the method addMaterialsInUsersInventory.

**Comment by adarshp** [comment]
Closing, superseded by #49

**Pull request closed without merging**
