### PR TITLE
Fixed the lagging behind of physio plots

### PR DESCRIPTION
**Pull request by manujinda**
Now physio plots gets chunks of samples accumulated while plotting the previous sample and only plots the last sample of each chunk skipping all the samples it did not get to in time.

Did some code cleanup and rearrangement.

### CODE REVIEW

**Comment by adarshp** [comment]
@manujinda  - it looks like the pull request was created. Did you mean that you were not able to merge the pull request into the `master` branch?

**Comment by CalebUAz** [comment]
@manujinda LGTM! 

@paulosoaresua could you please invoke  [run_physio_viz.sh](https://github.com/ml4ai/tomcat/blob/master/human_experiments/lab_software/tomcat-physio-viz/run_physio_viz.sh) with the uberscript?

Once that's done, @adarshp would merge it with the master.

**Comment by paulosoaresua** [comment]
@CalebUAz I think this should be closed and another ticket added to incorporate this in the uber script. I understand that we can run this manually from CAT, so this PR should be done IMO.

**Comment by CalebUAz** [comment]
> @CalebUAz I think this should be closed and another ticket added to incorporate this in the uber script. I understand that we can run this manually from CAT, so this PR should be done IMO.

Correct we can execute this manually from CAT. In that case @adarshp you can please proceed and merge it with the master?

**Comment by adarshp** [comment]
@CalebUAz - done.

**Pull request merged**
