### PR TITLE
Human experiments updates

### PR DESCRIPTION
**Pull request by CalebUAz**
Stuff Added:
1. `run_baseline_tasks_data_validation.py`: Checks all the folders, subfolders and CSV files generated by the baseline task. 
2. `EEG_plot.py`: Plots all EEG data streamed via LSL. 
3. Removed FFMPEG apple script `record_screen.scrpt` and migrated that to shell script `record_screen.sh`. 

Stuff updated:
1. All the config files (`config_affective_task.py`, `config_finger_tapping_task.py`, `config_ping_pong_task.py`, `config_rest_state.py`)under baseline task have a new variable called TOTAL_TIME which sums up the time taken by each task, this is used by the `run_baseline_tasks_data_validation.py`. 
2. `fNIRS_plot.py`: Has the appropriate setting for displaying fNIRS data in LangLab. 
3. `run_physio_viz.sh`: Add script that opens 3 instances of EEG viz plot along with fNIRS viz plot. 
4. `start_ffmpeg`: removed osascript and changed it to execute bash script. 
5. Renamed all `config_*.py` under every task to `config.py `.

### CODE REVIEW

**Review by adarshp — CHANGES_REQUESTED** [review]
Can you rename `config_affective_task.py` to `config.py` (and similarly with the other config files)? Since they are in their respective tasks' directories there shouldn't be any confusion.

**Comment by CalebUAz** [comment]
> Can you rename `config_affective_task.py` to `config.py` (and similarly with the other config files)? Since they are in their respective tasks' directories there shouldn't be any confusion.

Yes I pushed those changes!

**Review by adarshp — CHANGES_REQUESTED** [review]
Ah, sorry @CalebUAz  - just realized that my comment also applies to some of the other files. For example, could you rename `client_finger_tapping_task.py` to `client.py` (and similarly for the other client and server .py files)?

Once that is done, we can merge this PR into master.

**Comment by CalebUAz** [comment]
> Ah, sorry @CalebUAz - just realized that my comment also applies to some of the other files. For example, could you rename `client_finger_tapping_task.py` to `client.py` (and similarly for the other client and server .py files)?
> 
> Once that is done, we can merge this PR into master.

@adarshp Sure I can do that. I think its best to leave run_client.py and run_server.py. What do you think?

**Comment by adarshp** [comment]
@CalebUAz - I agree, let's leave `run_client.py` and `run_server.py` as they are.

**Comment by CalebUAz** [comment]
> @CalebUAz - I agree, let's leave `run_client.py` and `run_server.py` as they are.

I pushed those changes.

**Review by adarshp — APPROVED** [review]

**Pull request merged**
